### ISSUE TITLE
Missing articleList for some languages

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#285]
Some languages are missing their `medicine` articleList file on `/wp1` (some don't have an `xxwiki` folder at all):

Are those missing files or are those not candidates to WikiMed? And should thus be removed from zimfarm?

* http://download.kiwix.org/wp1/tawiki/customs/medicine
* http://download.kiwix.org/wp1/pawiki/customs/medicine
* http://download.kiwix.org/wp1/orwiki/customs/medicine
* http://download.kiwix.org/wp1/mrwiki/customs/medicine
* http://download.kiwix.org/wp1/bpywiki/customs/medicine
* http://download.kiwix.org/wp1/mlwiki/customs/medicine
* http://download.kiwix.org/wp1/knwiki/customs/medicine
* http://download.kiwix.org/wp1/guwiki/customs/medicine
* http://download.kiwix.org/wp1/aswiki/customs/medicine
* http://download.kiwix.org/wp1/lowiki/customs/medicine

**Comment by rgaudin** [comment]
* http://download.kiwix.org/wp1/azwiki/tops/50000

**Comment by rgaudin** [comment]
* http://download.kiwix.org/wp1/nanwiki/tops/50000
* http://download.kiwix.org/wp1/etwiki/tops/50000
* http://download.kiwix.org/wp1/elwiki/tops/50000
* http://download.kiwix.org/wp1/glwiki/tops/50000
* http://download.kiwix.org/wp1/glwiki/tops/50000
* http://download.kiwix.org/wp1/kawiki/tops/50000
* http://download.kiwix.org/wp1/lawiki/tops/50000
* http://download.kiwix.org/wp1/ltwiki/tops/50000
* http://download.kiwix.org/wp1/mkwiki/tops/50000
* http://download.kiwix.org/wp1/minwiki/tops/50000
* http://download.kiwix.org/wp1/nnwiki/tops/50000
* http://download.kiwix.org/wp1/cewiki/tops/50000
* http://download.kiwix.org/wp1/cywiki/tops/50000
* http://download.kiwix.org/wp1/slwiki/tops/50000
* http://download.kiwix.org/wp1/tawiki/tops/50000
* http://download.kiwix.org/wp1/azbwiki/tops/50000
* http://download.kiwix.org/wp1/vowiki/tops/50000

**Comment by kelson42** [comment]
@rgaudin The reason is that we currently provide wp1 data only for the 500K+ articles Wikipedias. I'll try to make data available for all Wikipedias.

**Comment by kelson42** [comment]
Fixed with https://github.com/openzim/wp1_selection_tools/commit/10ac628eb66d646908c14aa5924e539bdd6afabb

**Comment by rgaudin** [comment]
26 of them are still missing:

* 404 http://download.kiwix.org/wp1/pawiki/customs/medicine
* 404 http://download.kiwix.org/wp1/orwiki/customs/medicine
* 404 http://download.kiwix.org/wp1/mrwiki/customs/medicine
* 404 http://download.kiwix.org/wp1/bpywiki/customs/medicine
* 404 http://download.kiwix.org/wp1/mlwiki/customs/medicine
* 404 http://download.kiwix.org/wp1/knwiki/customs/medicine
* 404 http://download.kiwix.org/wp1/guwiki/customs/medicine
* 404 http://download.kiwix.org/wp1/aswiki/customs/medicine
* 404 http://download.kiwix.org/wp1/lowiki/customs/medicine
* 404 http://download.kiwix.org/wp1/azwiki/tops/50000
* 404 http://download.kiwix.org/wp1/nanwiki/tops/50000
* 404 http://download.kiwix.org/wp1/etwiki/tops/50000
* 404 http://download.kiwix.org/wp1/elwiki/tops/50000
* 404 http://download.kiwix.org/wp1/glwiki/tops/50000
* 404 http://download.kiwix.org/wp1/glwiki/tops/50000
* 404 http://download.kiwix.org/wp1/kawiki/tops/50000
* 404 http://download.kiwix.org/wp1/lawiki/tops/50000
* 404 http://download.kiwix.org/wp1/ltwiki/tops/50000
* 404 http://download.kiwix.org/wp1/mkwiki/tops/50000
* 404 http://download.kiwix.org/wp1/minwiki/tops/50000
* 404 http://download.kiwix.org/wp1/nnwiki/tops/50000
* 404 http://download.kiwix.org/wp1/cewiki/tops/50000
* 404 http://download.kiwix.org/wp1/cywiki/tops/50000
* 404 http://download.kiwix.org/wp1/slwiki/tops/50000
* 404 http://download.kiwix.org/wp1/azbwiki/tops/50000
* 404 http://download.kiwix.org/wp1/vowiki/tops/50000

**Comment by kelson42** [comment]
Yes, they are still not generated, this is normal. If next month they are still not there, then we have a problem.

**Comment by rgaudin** [comment]
OK ; leaving this open then.

**Comment by rgaudin** [comment]
It's next month and there are still not present.

**Comment by kelson42** [comment]
Done

**Comment by rgaudin** [comment]
Tried several of those links above and received 404...

**Comment by kelson42** [comment]
You have to wait tomorrow to get the permalink created/updated

**Comment by rgaudin** [comment]
Still missing:

* http://download.kiwix.org/wp1/tewiki/customs/medicine

**Comment by kelson42** [comment]
> Still missing:
> 
>     * http://download.kiwix.org/wp1/tewiki/customs/medicine

Not anymore
