### ISSUE TITLE
Worker/task CPU limits fail, workers are overloaded

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#351]
![BA1D9C20-8A69-474B-BD4A-F80A91B22FF7](https://user-images.githubusercontent.com/1029718/71446757-10f63480-2727-11ea-8ed9-e0945919f577.png)

**Comment by rgaudin** [comment]
fixed

**Comment by kelson42** [comment]
I reopen that issue as this is still not working and has a quite serious impact: ZIM files take far more time to be done than it should because worker's HW is overloaded.

**Comment by rgaudin** [comment]
All workers restarted on Feb 18 around 7pm UTC following gone-reporting fix.
Marking this as awaiting repro-case until it surfaces again and we can fix it for good.

**Comment by kelson42** [comment]
It makes 24 hours that the we don't have seen the problem occuring. I strongly believe it has vanished. I will reopen this ticket if not.
