### ISSUE TITLE
Recipe edit form consider there is always a pending modification

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#994]
Location: UI

See e.g. https://farm.openzim.org/recipes/iranwire.com_persian/edit

"Update Offliner details" button is always enabled while it should be only if there are pending modifications.

Looks like this is a zimit specific bug, or at least youtube, mwoffliner and sotoki are not impacted

Pending modification seems to be linked to `artifacts_globs`.

**Comment by elfkuzco** [comment]
@benoit74 , can you take a look at this? Seems to have been fixed as a consequence of the `zimfarm-upgrade`

**Comment by benoit74** [comment]
Issue is not really fixed because now whenever you change the `Artifacts` setting, the button to update configuration is never enabled. Looks like it is not possible to update this value anymore ...

<img width="551" height="193" alt="Image" src="https://github.com/user-attachments/assets/777b3b32-6528-428d-abe8-9916f965309b" />

This is obviously a blocker to deploy `zimfarm-upgrade` branch.
